name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        #active virtual environment
        poetry shell
    - name: Lint with blue
      run: |
        run blue .
    - name: Lint with isort
      run: |
        run isort --check .
    - name: Lint with flake8
      run: |
        run flake8 .
    - name: Test with pytest
      run: |
        run pytest
